# Generated by Django 5.2.4 on 2025-07-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evidence/')),
                ('is_authentic', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('metadata_status', models.CharField(blank=True, max_length=100)),
                ('blockchain_hash', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
