# Generated by Django 5.2.4 on 2025-07-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='created_at',
        ),
        migrations.AddField(
            model_name='evidence',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='blockchain_hash',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
