# Generated by Django 5.2.4 on 2025-07-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_app', '0002_remove_evidence_created_at_evidence_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='blockchain_hash',
        ),
        migrations.AddField(
            model_name='evidence',
            name='image_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
